apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-dp
  labels:
    app: vllm-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-dp
  template:
    metadata:
      labels:
        app: vllm-dp
    spec:
      containers:
      - name: rank0
        image: vllm/vllm-openai:v0.10.2
        args:
          - "--model=ibm-granite/granite-3.3-2b-instruct"
          - "--max-model-len=8192"
          - "--data-parallel-size=2"
          - "--data-parallel-rank=0"
          - "--port=8000"
        env:
        - name: VLLM_SERVER_DEV_MODE
          value: "1"
        - name: VLLM_CACHE_ROOT
          value: /tmp
        - name: FLASHINFER_WORKSPACE_BASE
          value: /tmp
        - name: XDG_CONFIG_HOME
          value: /tmp
        - name: TRITON_HOME
          value: /tmp
        - name: HF_HOME
          value: /tmp
        ports:
          - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: "2"
            memory: "16Gi"
          requests:
            cpu: "1"
            memory: "8Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
      - name: rank1
        image: vllm/vllm-openai:v0.10.2
        args:
          - "--model=ibm-granite/granite-3.3-2b-instruct"
          - "--max-model-len=8192"
          - "--data-parallel-size=2"
          - "--data-parallel-rank=1"
          - "--port=8001"
        env:
        - name: VLLM_SERVER_DEV_MODE
          value: "1"
        - name: VLLM_CACHE_ROOT
          value: /tmp
        - name: FLASHINFER_WORKSPACE_BASE
          value: /tmp
        - name: XDG_CONFIG_HOME
          value: /tmp
        - name: TRITON_HOME
          value: /tmp
        - name: HF_HOME
          value: /tmp
        ports:
          - containerPort: 8001
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: "2"
            memory: "16Gi"
          requests:
            cpu: "1"
            memory: "8Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 5
