apiVersion: v1
kind: Service
metadata:
  name: qwen2
  labels:
    app: qwen2
spec:
  type: NodePort
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: qwen2
